### ISSUE TITLE
Problems with POT Quantization

### ISSUE THREAD

**Issue by glucasol** [openvinotoolkit/openvino#17389]
Hi everyone,

I am having some problems to quantize my OpenVINO model with POT.

I have an anomaly detection model trained using this [Anomalib repo](https://github.com/openvinotoolkit/anomalib). I converted the trained model to OpenVINO format (.bin and .xml) with Model Optimizer MO. 

The structure of the dataset used to train/test the model is:

<ul>
  <li>Dataset Folder
  <ul>
  <li>Train
    <ul>
      <li>All normal images</li>
    </ul>
  </li>
  <li>Test
    <ul>
      <li>Normal <ul> <li>All good images</li> </ul></li>
      <li>Abnormal<ul> <li>All anomalous images</li> </ul></li>
    </ul>
  </li>
  <li>Masks
    <ul>
     <li>Abnormal<ul> <li>All anomalous masks</li> </ul></li>
    </ul>
  </li>
  </ul>
  </li>
</ul>

I want to run this POT command (As mentioned here: [POT](https://docs.openvino.ai/latest/pot_compression_cli_README.html) ):   `pot -c <path_to_config_file>`

I have created the .json configuration file like this [example](https://docs.openvino.ai/latest/pot_configs_examples_README.html)

But I need to have a config .yaml file, with is the Accuracy Checker configuration file.

So following this [Accuracy Checker Guide](https://docs.openvino.ai/latest/omz_tools_accuracy_checker.html#doxid-omz-tools-accuracy-checker), I need to create a config.yaml file similiar as below:
````
models:
- name: model_name
  launchers:
  - framework: openvino
    device: CPU
    model: path_to_model/alexnet.xml
    weights: path_to_weights/alexnet.bin
    adapter: anomaly_segmentation
  datasets:
    - name: dataset_name
      annotation: annotation.pickle
      data_source: images_folder

      preprocessing:
      - type: resize
        dst_width: 256
        dst_height: 256

      - type: normalization
        mean: imagenet

      - type: crop
        dst_width: 227
        dst_height: 227

     metrics:
     - type: accuracy
````

**After following all  these steps, I came up with some doubts:**
First, in launchers section, with adapter should I use, since my model is an anomaly detection model?
Second, in datasets section, what do I need to specify in annotation subsection, since I do not have an annotation file? [Anomalib](https://github.com/openvinotoolkit/anomalib) do not need annotation file, since the train dataset only has normal images and the test dataset is separated in normal and anomalous folders.

Can You help me with these doubts?

Thanks!
