### ISSUE TITLE
How can I Inference Bert Model in INT8 Mode???

### ISSUE THREAD

**Issue by NotMorven** [openvinotoolkit/openvino#1802]
**I have Bert model in Intermediate Representation (IR) format. When I used Post-training Optimization Tool to further optimize it, an error occurred as below:**
```
INFO:app.run:Output log dir: ./results\model_int8_DefaultQuantization\2020-08-17_11-20-46
INFO:app.run:Creating pipeline:
 Algorithm: DefaultQuantization
 Parameters:
        preset                     : performance
        stat_subset_size           : 300
        target_device              : CPU
        exec_log_dir               : ./results\model_int8_DefaultQuantization\2020-08-17_11-20-46
 ===========================================================================
Traceback (most recent call last):
  File "<path_to_env>\Anaconda3\envs\openvino\Scripts\pot-script.py", line 11, in <module>
    load_entry_point('pot==1.0', 'console_scripts', 'pot')()
  File "<path_to_env>\anaconda3\envs\openvino\lib\site-packages\pot-1.0-py3.6.egg\app\run.py", line 36, in main
    app(sys.argv[1:])
  File "<path_to_env>\anaconda3\envs\openvino\lib\site-packages\pot-1.0-py3.6.egg\app\run.py", line 55, in app
    metrics = optimize(config)
  File "<path_to_env>\anaconda3\envs\openvino\lib\site-packages\pot-1.0-py3.6.egg\app\run.py", line 110, in optimize
    data_loader = create_data_loader(config.engine, model)
  File "<path_to_env>\anaconda3\envs\openvino\lib\site-packages\pot-1.0-py3.6.egg\compression\data_loaders\creator.py", line 34, in create_data_loader
    'Actual inputs number: {}'.format(len(inputs)))
RuntimeError: IEEngine supports networks with single input or net with 2 inputs. In second case there are image input and image info input Actual inputs number: 3
```
**Bert has three input ports( input_ids, input_mask, segment_ids ), while POT only supports two at most. 
Is there any way to solve this problem???**

**Best regards, 
Morven**

**Comment by jgespino** [comment]
Hi @NotMorven 

Are you using the latest OpenVINO 2020.4 release? I'm not sure if there is another way to solve the error, let me check with my peers. 

Regards,
Jesus

**Comment by NotMorven** [comment]
> Hi @NotMorven
> 
> Are you using the latest OpenVINO 2020.4 release? I'm not sure if there is another way to solve the error, let me check with my peers.
> 
> Regards,
> Jesus

Hi @jgespino ,
I'm using 2020.3 release. Could the different versions be a possible reason? Looking forward to you reply.

Best regrads, 
Morven

**Comment by dmitryte** [comment]
Hi @NotMorven. 
@jgespino suggestion is correct - you should update to 2020.4 as bert was enabled for quantization and there some sample configs for pot there  - \deployment_tools\tools\post_training_optimization_toolkit\configs\examples\quantization\nlp

They can explain how to process your inputs properly(see accuracy_checker configuration that is being used internaly by pot - C:\Program Files (x86)\IntelSWTools\openvino_2020.4.287\deployment_tools\tools\post_training_optimization_toolkit\configs\examples\accuracy_checker\bert_base_squad_1_1_tf_int8.yml)

**Comment by NotMorven** [comment]
@dmitryte 
Got it. Thanks a lot!!!
By the way, has Inference Engine changed from version 2020.3 to 2020.4 ?

Morven

**Comment by dmitryte** [comment]
IE is being improved with every release to increase inference speed and keep accuracy of the original models on various hardware devices. You can check the whole list of new features and improvements in release notes - https://github.com/openvinotoolkit/openvino/releases/tag/2020.4

@NotMorven could you provide some feedback once you try to run pot with your bert model?

**Comment by NotMorven** [comment]
> IE is being improved with every release to increase inference speed and keep accuracy of the original models on various hardware devices. You can check the whole list of new features and improvements in release notes - https://github.com/openvinotoolkit/openvino/releases/tag/2020.4
> 
> @NotMorven could you provide some feedback once you try to run pot with your bert model?

Hi @dmitryte @jgespino 
Sorry, it's been a long time. I have updated OpenVINO to 2020.4. And the accuracy_checker file(bert_base_squad_1_1_tf_int8.yml) confused me. How can I make **'datasets' part** fit in with my own datasets. The BERT model is used for text classification tasks, followed with a linear layer, in my situation. 
```
# bert_base_squad_1_1_tf_int8.yml
models:
  - name: bert_base_squad1_1
    launchers:
      - framework: dlsdk
        device: cpu
        batch: 1
        adapter: classification
            # type: bert_question_answering
            # start_token_logits_output: "unstack/Squeeze_"
            # end_token_logits_output: "unstack/Split.1"
        mo_params:
            data_type: FP32
            input: input_ids,input_mask,segment_ids
            input_shape: "[1,512], [1,512], [1,512]"
            output: output/predictions
        mo_flags:
            - disable_nhwc_to_nchw
        inputs:
          - name: "input_ids"
            type: INPUT
            value: "input_ids"
            precision: I32
          - name: "input_mask"
            type: INPUT
            value: 'input_mask'
          - name: "segment_ids"
            type: INPUT
            value: 'segment_ids'
            precision: I32

    datasets:
      - name: squad
        data_source: <PATH_TO_DATASET>/squad1.1/
        annotation: <PATH_TO_DATASET>/squad.pickle
        reader:
            type: annotation_features_extractor
            features:
                - input_ids
                - input_mask
                - segment_ids
        postprocessing:
                - type: extract_answers_tokens
                  max_answer: 30
                  n_best_size: 20
        metrics:
            - name: 'F1'
              type: 'f1'
              reference: 88.57
              threshold: 0.01

            - name: 'EM'
              type: 'exact_match'
              reference: 81.25
              threshold: 0.01
```
**Or is there a way to directly quantify the BERT model without accuracy_checker part?**
```
//bert_base_squad_1_1_tf_int8.json
{
    "model": {
        ...
    },
    **"engine": {
        "config": "/root/chengzhi/OpenVINOTrial/int8_optimize/bert_int8/bert_base_squad_1_1_tf_int8.yml"
    },**
    "compression": {
        "target_device": "CPU",
        "algorithms": [
            {
                "name": "DefaultQuantization",
                "params": {
                    "preset": "accuracy",
                    // "preset": "performance",
                    "stat_subset_size": 1000,
                    ...
                    ...
                }
            }
        ]
    }
}
```

Morven

**Comment by whatisor** [comment]
Same question for me :
"Or is there a way to directly quantify the BERT model without accuracy_checker part(engine part), when using DefaultQuantization algorithm?"

Why do we need to force user to do with accuracy_checker??

**Comment by dmitryte** [comment]
@myshevts any ideas about bert quantization for classification task?

**Comment by dmitryte** [comment]
@NotMorven , @whatisor Hi!

Simple mode for quantization work only for models with 1 input-output and accepts images folder as an input.

For any BERT model you still need to describe the way to process inputs properly(check the docs for accuracy_checker to see how to adopt the config for your dataset - https://docs.openvinotoolkit.org/latest/omz_tools_accuracy_checker_README.html)

Btw, you can actually write all these parameters inside pot config file inside the engine section.

Here is a sample accuracy_checker config for classification, I think it's a good starting point.

```
models:
  - name: bert
    launchers:
      - framework: dlsdk
        adapter:
          type: bert_classification
          classification_out: loss/cls_logits/Add
          num_classes: 3
        inputs:
          - name: input_ids
            type: INPUT
            value: input_ids
          - name: input_mask
            type: INPUT
            value: input_mask
          - name: segment_ids
            type: INPUT
            value: segment_ids
    datasets:
      - name: xnli1.0
        reader:
          type: annotation_features_extractor
          features:
            - input_ids
            - input_mask
            - segment_ids
        metrics:
          - name: top1
            type: accuracy
            top_k: 1
```
