### ISSUE TITLE
[Bug]: Not able to load TensorFlow model on OpenVino model server

### ISSUE THREAD

**Issue by deepanshuhardaha** [openvinotoolkit/openvino#25346]
### OpenVINO Version

openvino/model_server:2024.2

### Operating System

Ubuntu 18.04 (LTS)

### Device used for inference

CPU

### Framework

Keras (TensorFlow 2)

### Model used

https://github.com/tensorflow/docs/blob/master/site/en/tutorials/quickstart/beginner.ipynb

### 🐛 Describe the bug

Before deploying our production model, we attempted to load a basic TensorFlow model on Kubernetes using the OpenVino model server image. I followed the steps from the official TensorFlow notebook [here](https://github.com/tensorflow/docs/blob/master/site/en/tutorials/quickstart/beginner.ipynb) to create a simple model. Afterward, I exported the model using the command:
`probability_model.export( "<gcs_base_path>/3")
`

I was able to load and infer this exported model using vanilla TensorFlow Serving (used `tensorflow/serving:2.16.1` image).

However, when deploying the same exported model on the OpenVino server, I encountered the following error
```
 Check 'is_conversion_successful' failed at src/frontends/tensorflow/src/frontend.cpp:478:
FrontEnd API failed with OpConversionFailure:
[TensorFlow Frontend] Internal error, conversion is failed for VarHandleOp operation with a message:
Variable or resource `sequential/dense_1/bias_1` is not initialized, model is inconsistent
```
<img width="1327" alt="Screenshot 2024-07-03 at 12 31 07 PM" src="https://github.com/openvinotoolkit/openvino/assets/82414442/d4cbce1f-a74c-49ef-8290-ea3e61010725">

### Environment

- TensorFlow version I used to export model: `2.16.1`
- Model server image: `openvino/model_server:2024.2`
- Machine where I am trying to host model on K8s: `n2-standard-8`

#### Exported model

You can find the exported model [here on Google Drive](https://drive.google.com/drive/folders/1ZpPw7OKxVIY0jjnM7xl3FpDcFGVw9NZ8?usp=sharing).

#### Container configuration snippet from deployment YAML
```
containers:
      - name: openVinoServer
        image: openvino/model_server:latest
        args:
        - --model_path=<gcs_base_path>
        - --model_name=dummy-tf
        - --port=8500
        - --target_device=CPU
```

Is this a bug or am I missing something?

Thanks!

### Issue submission checklist

- [X] I'm reporting an issue. It's not a question.
- [X] I checked the problem with the documentation, FAQ, open issues, Stack Overflow, etc., and have not found a solution.
- [X] There is reproducer code and related data files such as images, videos, models, etc.

**Comment by deepanshuhardaha** [comment]
I tried the [BERT](https://www.kaggle.com/models/tensorflow/bert) model downloaded from Kaggle on the same setup, and it is also failing with the same error
![image](https://github.com/openvinotoolkit/openvino/assets/82414442/bfa39057-7d75-4c28-b4fa-f044e5a9904e)

**Comment by Iffa-Intel** [comment]
@deepanshuhardaha could you provide:
1. Steps that you did to load a basic TensorFlow model on Kubernetes using the OpenVino model server image 
2. How you convert your model into OpenVINO format
3. Commands involved
4. Did you do any modifications to the model?

**Comment by deepanshuhardaha** [comment]
1. I used the following Kubernetes deployment YAML to load it
    <details>
    <summary>deployment.yaml</summary>
    
    ```
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: ovms-deployment
      namespace: <namespace>
      labels:
        service: ovms-deployment
    spec:
      replicas: 1
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 20%
          maxUnavailable: 10%
      selector:
        matchLabels:
          service: ovms-deployment
      template:
        metadata:
          labels:
            service-prometheus-track: ovms-deployment
          annotations:
            prometheus.io/scrape: 'true'
            prometheus.io/port: '8501'
            prometheus.io/path: /metrics
        spec:
          terminationGracePeriodSeconds: 30
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                    - key: service
                      operator: In
                      values:
                      - ovms-deployment
                  topologyKey: "kubernetes.io/hostname"
                weight: 100
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - preference:
                  matchExpressions:
                  - key: cloud.google.com/gke-preemptible
                    operator: Exists
                weight: 100
          containers:
          - name: openVinoServer
            image: openvino/model_server:latest
            args:
            - --model_path=<gcs_base_path_of_saved_model.pb_file>
            - --model_name=dummy-tf
            - --port=8500
            - --target_device=CPU
            imagePullPolicy: Always
            ports:
            - containerPort: 8500
              name: grpc
              protocol: TCP
            - containerPort: 8501
              name: http
              protocol: TCP
            env: 
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: <path>
            - name: RANDOM_UUID
              value: ${ parameters["random_uuid"] }
            resources: 
              limits:
                cpu: 10000m
                memory: 10Gi
              requests:
                cpu: 5000m
                memory: 5Gi
          terminationGracePeriodSeconds: 35
    ```
    </details>
2. I didn't convert the TensorFlow model into OpenVino format because the OpenVino [documentation](https://docs.openvino.ai/2024/openvino-workflow/model-preparation.html#different-model-representations) states that we can skip model conversion and run inference directly from the TensorFlow source format.
3. I did not use any commands to convert or host the model on OVMS.
4. It's exactly as the tutorial I shared. I didn't modify anything.
